function[Cl] = clsectional(alpha, aerofoil_properties)

% this function generates a sectional lift coefficient at a user specified
% angle of attack. The profile of the sectional lift coefficient curve
% is generated by blending thin aerofoil theory with flat plate theory,
% can can be controlled with the six inputs specified below. 
% These can be considered as rough guidelines for the shape of the curve

alphastall = aerofoil_properties(1);    % +ve alpha stall angle    [rad]
deltaalpha = aerofoil_properties(2);    % +ve stall region width   [rad]
alphastall2 = aerofoil_properties(3);   % -ve alpha stall angle    [rad]
deltaalpha2 = aerofoil_properties(4);   % -ve stall region width   [rad]
visceff = aerofoil_properties(5);       % viscous correction factor
phaseshift = aerofoil_properties(6);    % camber adjustment        [rad]

% blending function for positive alpha stall region
f=(0.5*(1+tanh((alpha-alphastall)/deltaalpha)));
% blending function for negative alpha stall region
h=(0.5*(1+tanh((alpha-alphastall2)/deltaalpha2)));
% step function - to activate blending functions f and h 
g=-tanh((alpha)/1e-10);

% Cl for positive alpha range
Clpositivealpha=((1-f).*visceff*2*pi.*(alpha+phaseshift)...
    +2*(f).*sin(alpha).*cos(alpha));         
% Cl for negative alpha range
Clnegativealpha=((h).*visceff*2*pi.*(alpha+phaseshift))...
    +2*(1-h).*sin(alpha).*cos(alpha);                     
% full Cl range
Cl=Clpositivealpha.*0.5.*(1-g)+Clnegativealpha.*0.5.*(g+1);
